# Generated by Django 4.2.30 on 2026-05-14 05:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesPanelSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_quota', models.DecimalField(decimal_places=2, default=10000.0, max_digits=10)),
                ('theme_preference', models.CharField(default='light', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sales_panel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ManagerPanelSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_revenue_target', models.DecimalField(decimal_places=2, default=100000.0, max_digits=12)),
                ('report_frequency', models.CharField(default='weekly', max_length=20)),
                ('theme_preference', models.CharField(default='light', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager_panel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdminPanelSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_revenue_target', models.DecimalField(decimal_places=2, default=1000000.0, max_digits=15)),
                ('enable_notifications', models.BooleanField(default=True)),
                ('theme_preference', models.CharField(default='light', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_panel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
