# Generated by Django 4.2.30 on 2026-05-14 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
