# Generated by Django 4.2.30 on 2026-05-15 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0004_deal_deleted_at_deal_is_deleted_lead_deleted_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='role',
        ),
        migrations.AddField(
            model_name='contact',
            name='industry',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contact',
            name='last_contacted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contact',
            name='size',
            field=models.CharField(blank=True, help_text='e.g., Enterprise, Mid-Market', max_length=50),
        ),
        migrations.AddField(
            model_name='contact',
            name='website',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lead',
            name='company',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Follow-up', 'Follow-up'), ('Qualified', 'Qualified'), ('Meeting', 'Meeting'), ('Requirements', 'Requirements'), ('Proposal', 'Proposal'), ('Negotiation', 'Negotiation'), ('Won', 'Won'), ('Lost', 'Lost')], default='New', max_length=20),
        ),
    ]
