# Generated by Django 4.2.30 on 2026-05-16 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_alter_contact_designation_alter_contact_linkedin_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='industry',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
