# Generated by Django 4.2.30 on 2026-05-18 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_lead_industry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['-created_at']},
        ),
    ]
