# Generated by Django 4.2.30 on 2026-05-18 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_lead_score_task_progress_percentage_task_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(blank=True, default='Yet to approach', max_length=500),
        ),
    ]
