# Generated by Django 4.2.30 on 2026-05-14 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('territory', models.CharField(blank=True, help_text='e.g., West Coast, New York', max_length=100)),
                ('target_quota', models.DecimalField(decimal_places=2, default=10000.0, max_digits=12)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=5.0, help_text='Percentage', max_digits=5)),
                ('manager', models.ForeignKey(blank=True, limit_choices_to={'role': 'MANAGER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_sales_profiles', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sales_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ManagerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(blank=True, help_text='e.g., North America, EMEA', max_length=100)),
                ('team_budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('max_team_size', models.PositiveIntegerField(default=10)),
                ('monthly_target', models.DecimalField(decimal_places=2, default=50000.0, max_digits=12)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, help_text='e.g., IT, Operations, Executive', max_length=100)),
                ('access_level', models.CharField(default='Super Admin', max_length=50)),
                ('can_manage_billing', models.BooleanField(default=True)),
                ('can_manage_users', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
